# /// script
# requires-python = ">=3.11"
# dependencies = [
#   "numpy",
#   "opencv-python-headless",
# ]
# ///

"""Generate the throwaway firmware's embedded RGB565 ArUco marker."""

from pathlib import Path

import cv2
import numpy as np

IMAGE_SIZE = 320
QUIET_ZONE = 40
SYMBOL_SIZE = IMAGE_SIZE - 2 * QUIET_ZONE
GRAY = 200
OUTPUT = Path(__file__).resolve().parents[1] / "main" / "proto_marker.h"


def rgb565(gray: int) -> int:
    return ((gray >> 3) << 11) | ((gray >> 2) << 5) | (gray >> 3)


def main() -> None:
    dictionary = cv2.aruco.getPredefinedDictionary(cv2.aruco.DICT_4X4_50)
    symbol = cv2.aruco.generateImageMarker(dictionary, 0, SYMBOL_SIZE)
    image = np.full((IMAGE_SIZE, IMAGE_SIZE), GRAY, dtype=np.uint8)
    image[
        QUIET_ZONE : QUIET_ZONE + SYMBOL_SIZE,
        QUIET_ZONE : QUIET_ZONE + SYMBOL_SIZE,
    ] = np.where(symbol > 0, GRAY, 0)

    pixels = [rgb565(int(value)) for value in image.flat]
    lines = [
        "// Generated by tools/gen_marker.py. Do not edit.",
        "#pragma once",
        "",
        "#include <stdint.h>",
        "",
        f"#define PROTO_MARKER_WIDTH {IMAGE_SIZE}",
        f"#define PROTO_MARKER_HEIGHT {IMAGE_SIZE}",
        f"#define PROTO_MARKER_QUIET_ZONE {QUIET_ZONE}",
        f"#define PROTO_MARKER_SYMBOL_SIZE {SYMBOL_SIZE}",
        "",
        "static const uint16_t proto_marker[PROTO_MARKER_WIDTH * PROTO_MARKER_HEIGHT] = {",
    ]
    for offset in range(0, len(pixels), 16):
        chunk = ", ".join(f"0x{value:04X}" for value in pixels[offset : offset + 16])
        lines.append(f"    {chunk},")
    lines.extend(["};", ""])
    OUTPUT.write_text("\n".join(lines))
    print(f"wrote {OUTPUT} ({IMAGE_SIZE}x{IMAGE_SIZE}, {QUIET_ZONE}px quiet zone)")


if __name__ == "__main__":
    main()
