# /// script
# requires-python = ">=3.11"
# dependencies = ["numpy"]
# ///
"""THROWAWAY: generate main/proto_badge.h — per-device ID badges for the AMOLED.

Renders 'A' (amber) and 'B' (blue) plus '?' (white) as RGB565 bitmaps for the
~64px band below the marker asset. Device firmware picks the badge by chip MAC.
"""
import numpy as np

W, H = 368, 56  # bottom band, leaves margin below the 320px marker asset
LETTER_W, LETTER_H, STROKE = 30, 44, 8

def rgb565(r, g, b):
    return ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)

COLORS = {"A": rgb565(255, 150, 0), "B": rgb565(60, 140, 255), "Q": rgb565(230, 230, 230)}

def draw_letter(canvas, letter, x0, y0, color):
    x1, y1 = x0 + LETTER_W, y0 + LETTER_H
    s = STROKE
    if letter == "A":
        canvas[y0:y1, x0:x0 + s] = color          # left leg
        canvas[y0:y1, x1 - s:x1] = color          # right leg
        canvas[y0:y0 + s, x0:x1] = color          # top
        my = y0 + LETTER_H // 2
        canvas[my:my + s, x0:x1] = color          # crossbar
    elif letter == "B":
        canvas[y0:y1, x0:x0 + s] = color          # spine
        canvas[y0:y0 + s, x0:x1 - 4] = color      # top
        my = y0 + LETTER_H // 2
        canvas[my - s // 2:my + s // 2, x0:x1 - 4] = color  # middle
        canvas[y1 - s:y1, x0:x1 - 4] = color      # bottom
        canvas[y0:my, x1 - s - 4:x1 - 4] = color  # upper bowl
        canvas[my:y1, x1 - s:x1] = color          # lower bowl
    else:  # '?'
        canvas[y0:y0 + s, x0:x1] = color
        canvas[y0:y0 + LETTER_H // 2, x1 - s:x1] = color
        my = y0 + LETTER_H // 2
        mx = (x0 + x1) // 2
        canvas[my:my + s, mx - s // 2:x1] = color
        canvas[y1 - s:y1, mx - s // 2:mx + s // 2] = color

def badge(letter):
    canvas = np.zeros((H, W), dtype=np.uint16)
    color = COLORS[letter if letter in COLORS else "Q"]
    # thin full-width color band + centered letter
    canvas[H - 6:H, :] = color
    canvas[0:6, :] = color
    draw_letter(canvas, letter, (W - LETTER_W) // 2, 6, color)
    return canvas

with open("main/proto_badge.h", "w") as f:
    f.write("// Generated by tools/gen_badge.py — device ID badges (RGB565)\n")
    f.write("#pragma once\n#include <stdint.h>\n")
    f.write(f"#define BADGE_WIDTH {W}\n#define BADGE_HEIGHT {H}\n")
    for name, letter in (("A", "A"), ("B", "B"), ("UNKNOWN", "Q")):
        data = badge(letter).flatten()
        f.write(f"static const uint16_t badge_{name.lower()}[BADGE_WIDTH * BADGE_HEIGHT] = {{\n")
        for i in range(0, len(data), 12):
            f.write("    " + ", ".join(f"0x{v:04X}" for v in data[i:i + 12]) + ",\n")
        f.write("};\n")
print("wrote main/proto_badge.h")
